---
# PostgreSQL secret
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: apps-dev
type: Opaque
stringData:
  password: "db_password"
---
# Keycloak admin secret
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  namespace: apps-dev
type: Opaque
stringData:
  admin-password: "admin"
---
# Hint backend secrets
apiVersion: v1
kind: Secret
metadata:
  name: hint-backend-secret
  namespace: apps-dev
type: Opaque
stringData:
  postgres-user: "db_user"
  postgres-password: "db_password"
---
# DLT backend secrets
apiVersion: v1
kind: Secret
metadata:
  name: dlt-backend-secret
  namespace: apps-dev
type: Opaque
stringData:
  postgres-user: "db_user"
  postgres-password: "db_password"
