---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hint-backend-config
  namespace: apps-dev
data:
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_DB_NAME: "hint"
  POSTGRES_SCHEMA_NAME: "hint"
  KAFKA_BROKERS: "kafka:9092"
  KAFKA_CONSUMER_GROUP: "kafka-elpa-hint"
  KAFKA_PROTOCOL: "PLAINTEXT"
  KAFKA_JAAS_ENABLED: "false"
  AUTH_URL: "http://keycloak:8080/realms/lab/"
  AUTH_USERS: "admin"
  SWAGGER_ENABLED: "true"
  FLYWAY_ENABLED: "true"
  FLYWAY_LOCATIONS: "db/migration"
  FLYWAY_ROLE: "db_user"
  SERVICE_NAME: "hint-service"
  LOG_LEVEL: "INFO"
  LOG_LEVEL_SI: "DEBUG"
  LOGBACK_FILE: "logback-plain.xml"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hint-backend
  namespace: apps-dev
  labels:
    app: hint-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hint-backend
  template:
    metadata:
      labels:
        app: hint-backend
      annotations:
        sidecar.istio.io/inject: "true"
        prometheus.io/scrape: "true"
        prometheus.io/port: "8081"
        prometheus.io/path: "/metrics/prometheus"
    spec:
      containers:
        - name: hint-backend
          image: lab/hint-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 8081
              name: management
          envFrom:
            - configMapRef:
                name: hint-backend-config
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: hint-backend-secret
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hint-backend-secret
                  key: postgres-password
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 5
          startupProbe:
            httpGet:
              path: /health/readiness
              port: 8081
            failureThreshold: 18
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: hint-backend
  namespace: apps-dev
spec:
  selector:
    app: hint-backend
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: management
      port: 8081
      targetPort: 8081
  type: ClusterIP
