import de.signaliduna.BitbucketRepo
import de.signaliduna.CopsiEnvironment
import groovy.json.JsonOutput
import groovy.json.JsonSlurperClassic
import groovy.transform.Field

@Field
String CERT_FILE_NOP = "https://git.system.local/projects/CP/repos/sealed-secrets-keys/raw/public-key-nop?at=refs%2Fheads%2Fmain"

@Field
String CERT_FILE_PRD = "https://git.system.local/projects/CP/repos/sealed-secrets-keys/raw/public-key-prd?at=refs%2Fheads%2Fmain"

@Field
String GIT_CLONE_DIR = "cd-repos"

@Field
String GIT_CREDENTIALS_ID = "jenkins_git_http"

// Lab: Gitea API base. Corporate: Bitbucket REST API.
// The env var GIT_API_BASE allows switching without code change.
@Field
String GIT_API_BASE = env?.GIT_API_BASE ?: "http://gitea:3000/api/v1"

@Field
String GIT_SERVER_URL = env?.GIT_SERVER_URL ?: "http://gitea:3000"

String getSealedSecretCertFile(CopsiEnvironment clusterName) {
    if (clusterName == CopsiEnvironment.prd) {
        return CERT_FILE_PRD
    }
    return CERT_FILE_NOP
}

String getSealedSecretCertFile(String clusterName) {
    return getSealedSecretCertFile(CopsiEnvironment.valueOf(clusterName))
}

void writeSealedSecretFile(Map config) {
    def secretContent = [
            'apiVersion': 'v1',
            'kind': 'Secret',
            'metadata': [
                    'name': config.name,
                    'namespace': config.namespace,
                    'annotations': [
                            'sealedsecrets.bitnami.com/managed': 'true',
                            'sealedsecrets.bitnami.com/namespace-wide': 'true'
                    ]
            ],
            'data': config.secretData.collectEntries { entry -> ["${entry.key}": entry.value.bytes.encodeBase64().toString()] }
    ]
    String prefix = config.containsKey("prefix") ? config.prefix : "# This file has been automatically generated by jenkins_shared_libraries module si_copsi"
    prefix = prefix?.trim() ? "$prefix\n" : ""

    withEnv(["PATH=${PATH}:/tools"]) {
        String secretAsYaml = writeYaml data: secretContent, returnText: true
        String sealedSecretAsYaml = sh script: "echo '${secretAsYaml}' | kubeseal --format yaml --cert='${config.certFile}'", returnStdout: true

        String outputFolder = new File(config.outputFile).getParent()
        sh "mkdir -p ${outputFolder}"
        writeFile file: config.outputFile, text: prefix + sealedSecretAsYaml, encoding: "UTF-8"
    }
}

boolean createChange(BitbucketRepo repo, String targetBranch, Closure<String> updater) {
    sh "mkdir -p ${GIT_CLONE_DIR}"
    dir(GIT_CLONE_DIR) {
        withCredentials([gitUsernamePassword(credentialsId: GIT_CREDENTIALS_ID)]) {
            def gitUrl = buildGitUrl("${GIT_SERVER_URL}/scm/${repo.projectName}/${repo.repoName}.git")
            sh "rm -rf ${repo.repoName}"
            sh "git clone ${gitUrl} --depth 1 -b '${targetBranch}'"
            dir(repo.repoName) {
                sh "git config user.email 'jenkins@lab.local'"
                sh "git config user.name 'Jenkins Lab'"
                String commitMessage = updater()
                sh "git commit --allow-empty -m '${commitMessage}'"

                String changedFiles = sh(script: "git diff --name-only ${targetBranch} origin/${targetBranch}", returnStdout: true).trim()
                if (changedFiles) {
                    echo "The following files changed:"
                    echo "${changedFiles}"

                    sh 'git push -u origin HEAD'
                    return true
                } else {
                    echo "No changes between the local and remote branches."
                    return false
                }
            }
        }
    }
}

String createChangeAsPullRequest(BitbucketRepo repo, String sourceBranch = "autodeploy/job-${BUILD_NUMBER}", String targetBranch, Map pullRequestAttributes, Closure<String> updater) {
    sh "mkdir -p ${GIT_CLONE_DIR}"
    String prId = ""
    dir(GIT_CLONE_DIR) {
        withCredentials([gitUsernamePassword(credentialsId: GIT_CREDENTIALS_ID)]) {
            def gitUrl = buildGitUrl("${GIT_SERVER_URL}/scm/${repo.projectName}/${repo.repoName}.git")
            sh "rm -rf ${repo.repoName}"
            sh "git clone ${gitUrl} --depth 1 -b '${targetBranch}'"
            dir(repo.repoName) {
                sh "git config user.email 'jenkins@lab.local'"
                sh "git config user.name 'Jenkins Lab'"
                sh "git checkout -b '${sourceBranch}'"
                String commitMessage = updater()
                sh "git commit --allow-empty -m '${commitMessage}'"

                String changedFiles = sh(script: "git diff --name-only ${sourceBranch} origin/${targetBranch}", returnStdout: true).trim()
                if (changedFiles) {
                    echo "The following files changed:"
                    echo "${changedFiles}"

                    sh 'git push -u origin HEAD'
                    prId = createPullRequest(repo, sourceBranch, targetBranch, pullRequestAttributes)
                } else {
                    echo "No changes between the local and remote branches."
                }
            }
        }
    }

    return prId
}

String createPullRequest(BitbucketRepo repo, String sourceBranch, String targetBranch, Map pullRequestAttributes) {
    def defaultPullRequestAttributes = [
        title: "Autodeploy ${BUILD_NUMBER}",
        description: "Autodeploy for build number ${BUILD_NUMBER}"
    ]

    // Gitea API format: flat head/base
    // Bitbucket format: nested fromRef/toRef — handled by the API adapter below
    def requestBody = buildPullRequestBody(defaultPullRequestAttributes + pullRequestAttributes, repo, sourceBranch, targetBranch)
    def requestBodyAsJson = JsonOutput.toJson(requestBody)

    def apiUrl = buildPullRequestUrl(repo)
    def request = httpRequest httpMode: 'POST', url: apiUrl, authentication: GIT_CREDENTIALS_ID, validResponseCodes: '200:201', contentType: "APPLICATION_JSON", requestBody: requestBodyAsJson
    def response = new JsonSlurperClassic().parseText(request.content)

    // Gitea returns 'number', Bitbucket returns 'id'
    return (response.number ?: response.id).toString()
}

boolean waitForMergeChecksAndMerge(BitbucketRepo repo, String prId, boolean abortBuildOnError = false, boolean deleteSourceBranch = true, int maxAttempts = 30) {
    sleep(time: 5, unit: "SECONDS")

    int attempts = 0

    while (attempts < maxAttempts) {
        def prStatus = getPullRequestMergeStatus(repo, prId)

        if (prStatus == null) {
            if (abortBuildOnError) {
                error("Error retrieving PR information for PR ${prId}")
            }
            return false
        }

        if (canMerge(prStatus)) {
            def mergeResponse = mergePullRequest(repo, prId, prStatus, deleteSourceBranch)
            if (mergeResponse != null) {
                return true
            } else {
                if (abortBuildOnError) {
                    error("Error merging PR ${prId}")
                }
                return false
            }
        }

        sleep(time: 1, unit: "SECONDS")
        attempts++
    }

    if (abortBuildOnError) {
        currentBuild.result = "ABORTED"
        error("Timeout waiting for merge conditions for PR ${prId}")
    }
    return false
}

Map getPullRequestMergeStatus(BitbucketRepo repo, String prId) {
    def url = buildMergeStatusUrl(repo, prId)
    try {
        def request = httpRequest httpMode: 'GET', url: url, authentication: GIT_CREDENTIALS_ID, validResponseCodes: '200'
        return new JsonSlurperClassic().parseText(request.content)
    } catch (Exception ex) {
        println("Error retrieving ${url}: ${ex.message}")
        return null
    }
}

Map getPullRequestInfo(BitbucketRepo repo, String prId) {
    def url = buildPullRequestInfoUrl(repo, prId)
    try {
        def request = httpRequest httpMode: 'GET', url: url, authentication: GIT_CREDENTIALS_ID, validResponseCodes: '200'
        return new JsonSlurperClassic().parseText(request.content)
    } catch (Exception ex) {
        println("Error retrieving ${url}: ${ex.message}")
        return null
    }
}

String mergePullRequest(BitbucketRepo repo, String prId, def prStatus, boolean deleteSourceBranch) {
    def url = buildMergeUrl(repo, prId)
    def requestBody = buildMergeBody(prStatus, deleteSourceBranch)
    def requestBodyAsJson = JsonOutput.toJson(requestBody)

    try {
        def request = httpRequest(httpMode: 'POST', url: url, authentication: GIT_CREDENTIALS_ID, validResponseCodes: '200:204', contentType: "APPLICATION_JSON", requestBody: requestBodyAsJson)

        // Gitea merge returns empty body on success
        if (request.content?.trim()) {
            def response = new JsonSlurperClassic().parseText(request.content)
            return (response.number ?: response.id)?.toString()
        }
        return prId
    } catch (Exception ex) {
        println("Error merging ${url}: ${ex.message}")
        return null
    }
}

// ============================================================
// Git platform adapter — only these private methods differ
// between Bitbucket and Gitea.
// ============================================================

private boolean isGitea() {
    return GIT_API_BASE.contains("/api/v1")
}

private boolean canMerge(Map prStatus) {
    if (isGitea()) {
        // Gitea: mergeable field on the PR itself
        return prStatus.mergeable != false
    } else {
        // Bitbucket: canMerge field on merge status endpoint
        return prStatus.canMerge
    }
}

private Map buildPullRequestBody(Map attrs, BitbucketRepo repo, String sourceBranch, String targetBranch) {
    if (isGitea()) {
        return [
            title: attrs.title,
            body : attrs.description ?: "",
            head : sourceBranch,
            base : targetBranch
        ]
    } else {
        return attrs + [
            fromRef: [id: sourceBranch, repository: [slug: repo.repoName, name: null, project: [key: "${repo.projectName}"]]],
            toRef:   [id: targetBranch, repository: [slug: repo.repoName, name: null, project: [key: "${repo.projectName}"]]],
            close_source_branch: true
        ]
    }
}

private Map buildMergeBody(def prStatus, boolean deleteSourceBranch) {
    if (isGitea()) {
        return [Do: "merge", delete_branch_after_merge: deleteSourceBranch]
    } else {
        def version = prStatus.version ?: getPullRequestInfo(null, null)?.version
        return [context: [], version: version]
    }
}

private String buildPullRequestUrl(BitbucketRepo repo) {
    if (isGitea()) {
        return "${GIT_API_BASE}/repos/${repo.projectName}/${repo.repoName}/pulls"
    } else {
        return "${GIT_API_BASE}/${repo.projectName}/repos/${repo.repoName}/pull-requests"
    }
}

private String buildPullRequestInfoUrl(BitbucketRepo repo, String prId) {
    if (isGitea()) {
        return "${GIT_API_BASE}/repos/${repo.projectName}/${repo.repoName}/pulls/${prId}"
    } else {
        return "${GIT_API_BASE}/${repo.projectName}/repos/${repo.repoName}/pull-requests/${prId}"
    }
}

private String buildMergeStatusUrl(BitbucketRepo repo, String prId) {
    if (isGitea()) {
        // Gitea: PR info endpoint includes mergeable field
        return "${GIT_API_BASE}/repos/${repo.projectName}/${repo.repoName}/pulls/${prId}"
    } else {
        return "${GIT_API_BASE}/${repo.projectName}/repos/${repo.repoName}/pull-requests/${prId}/merge"
    }
}

private String buildMergeUrl(BitbucketRepo repo, String prId) {
    if (isGitea()) {
        return "${GIT_API_BASE}/repos/${repo.projectName}/${repo.repoName}/pulls/${prId}/merge"
    } else {
        return "${GIT_API_BASE}/${repo.projectName}/repos/${repo.repoName}/pull-requests/${prId}/merge"
    }
}

String buildGitUrl(String gitUrl) {
    if (isGitea()) {
        // Gitea: rewrite /scm/org/repo.git → /org/repo.git (Gitea doesn't use /scm/ prefix)
        return gitUrl.replaceFirst('/scm/', '/')
    }

    def knownLegacyJenkinsUrls = [
            'https://ci.system.local/'
    ]
    boolean isLegacyJenkins = knownLegacyJenkinsUrls.any { env.JENKINS_URL?.startsWith(it) }

    if (isLegacyJenkins) {
        echo "Build läuft auf einem Legacy-Jenkins-Server unter ci.system.local/[TEAM]. Git-URL wird um Credentials erweitert."
        return gitUrl.replaceFirst('https://', "https://${URLEncoder.encode(env.GIT_USERNAME, 'UTF-8')}:${URLEncoder.encode(env.GIT_PASSWORD, 'UTF-8')}@")
    } else {
        echo "Build läuft auf dem SDA-Jenkins-Server (sda-jenkins.system.local). Git-URL wird nicht verändert."
        return gitUrl
    }
}
